# Generated by Django 5.2 on 2026-07-29 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='описание')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='доступные модули')),
                ('readonly', models.JSONField(blank=True, default=list, verbose_name='только чтение')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('login', models.CharField(max_length=64, unique=True, verbose_name='логин')),
                ('full_name', models.CharField(max_length=180, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='телефон')),
                ('two_factor', models.BooleanField(default=False, verbose_name='двухфакторная аутентификация')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='доступ в админку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('companies', models.ManyToManyField(blank=True, related_name='users', to='directories.company', verbose_name='организации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='роль')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('full_name',),
            },
        ),
    ]
