# Generated by Django 5.2 on 2026-07-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=60, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата заключения')),
                ('side', models.CharField(choices=[('client', 'С покупателем'), ('supplier', 'С поставщиком')], default='client', max_length=16, verbose_name='сторона')),
                ('type', models.CharField(blank=True, default='', max_length=80, verbose_name='тип договора')),
                ('subject', models.TextField(blank=True, default='', verbose_name='предмет договора')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('currency', models.CharField(default='KGS', max_length=8, verbose_name='валюта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('end_date', models.DateField(verbose_name='действует до')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='автопролонгация')),
                ('signed', models.BooleanField(default=False, verbose_name='подписан')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('expired', 'Истёк'), ('closed', 'Закрыт')], default='active', max_length=16, verbose_name='статус')),
                ('responsible', models.CharField(blank=True, default='', max_length=180, verbose_name='ответственный')),
                ('template', models.CharField(blank=True, default='', max_length=120, verbose_name='шаблон')),
                ('notes', models.TextField(blank=True, default='', verbose_name='примечания')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='directories.counterparty', verbose_name='контрагент')),
            ],
            options={
                'verbose_name': 'договор',
                'verbose_name_plural': 'договоры',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=60, verbose_name='номер')),
                ('type', models.CharField(choices=[('invoice', 'Счёт на оплату'), ('waybill', 'Накладная'), ('act', 'Акт выполненных работ'), ('contract', 'Договор'), ('payment', 'Платёжный документ'), ('cash_order', 'Кассовый ордер'), ('vat_invoice', 'Счёт-фактура'), ('poa', 'Доверенность'), ('hr', 'Кадровый документ')], default='invoice', max_length=24, verbose_name='тип')),
                ('type_name', models.CharField(blank=True, default='', max_length=80, verbose_name='название типа')),
                ('date', models.DateField(verbose_name='дата')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('posted', 'Проведено')], default='draft', max_length=16, verbose_name='статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='файл')),
                ('file_name', models.CharField(blank=True, default='', max_length=180, verbose_name='имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='размер, КБ')),
                ('ocr', models.BooleanField(default=False, verbose_name='распознан')),
                ('ocr_text', models.TextField(blank=True, default='', verbose_name='распознанный текст')),
                ('signed', models.BooleanField(default=False, verbose_name='подписан ЭЦП')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='метки')),
                ('route', models.JSONField(blank=True, default=list, verbose_name='маршрут согласования')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='история изменений')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='directories.counterparty', verbose_name='контрагент')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('doc_number', models.CharField(blank=True, default='', max_length=60, verbose_name='номер документа')),
                ('doc_type', models.CharField(blank=True, default='', max_length=80, verbose_name='тип документа')),
                ('signer', models.CharField(max_length=180, verbose_name='подписал')),
                ('cert', models.CharField(max_length=80, verbose_name='сертификат')),
                ('issuer', models.CharField(blank=True, default='', max_length=180, verbose_name='издатель')),
                ('algorithm', models.CharField(blank=True, default='ГОСТ Р 34.10-2012', max_length=60, verbose_name='алгоритм')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действителен до')),
                ('ts', models.DateTimeField(verbose_name='дата подписи')),
                ('valid', models.BooleanField(default=True, verbose_name='подпись действительна')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document', verbose_name='документ')),
            ],
            options={
                'verbose_name': 'электронная подпись',
                'verbose_name_plural': 'электронные подписи',
                'ordering': ('-ts',),
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type'], name='documents_d_type_22a1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['date'], name='documents_d_date_e55297_idx'),
        ),
    ]
