# Generated by Django 5.2 on 2026-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('invoice', 'Счёт на оплату'), ('waybill', 'Накладная'), ('act', 'Акт выполненных работ'), ('contract', 'Договор'), ('payment', 'Платёжный документ'), ('cash_order', 'Кассовый ордер'), ('vat_invoice', 'Счёт-фактура'), ('poa', 'Доверенность'), ('statement', 'Банковская выписка'), ('hr', 'Кадровый документ')], default='invoice', max_length=24, verbose_name='тип'),
        ),
    ]
