# Generated by Django 5.2 on 2026-07-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('title', models.CharField(max_length=255, verbose_name='название сделки')),
                ('stage', models.CharField(choices=[('new', 'Новая'), ('contact', 'Контакт установлен'), ('offer', 'КП отправлено'), ('negotiation', 'Переговоры'), ('won', 'Выиграна'), ('lost', 'Проиграна')], default='new', max_length=16, verbose_name='стадия')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('probability', models.PositiveSmallIntegerField(default=10, verbose_name='вероятность, %')),
                ('manager', models.CharField(blank=True, default='', max_length=180, verbose_name='менеджер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('next_step', models.CharField(blank=True, default='', max_length=180, verbose_name='следующий шаг')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='дата шага')),
                ('activities', models.JSONField(blank=True, default=list, verbose_name='история общения')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='directories.counterparty', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'сделка',
                'verbose_name_plural': 'сделки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='товары')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма без скидки')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='скидка')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='итого')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='в том числе НДС')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='оплачено')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='срок оплаты')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('partial', 'Частично'), ('unpaid', 'Не оплачено')], default='unpaid', max_length=16, verbose_name='статус оплаты')),
                ('manager', models.CharField(blank=True, default='', max_length=180, verbose_name='менеджер')),
                ('posted', models.BooleanField(default=False, verbose_name='проведён')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='directories.counterparty', verbose_name='клиент')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='directories.warehouse', verbose_name='склад отгрузки')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата')),
                ('sale_number', models.CharField(blank=True, default='', max_length=40, verbose_name='номер продажи')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма возврата')),
                ('reason', models.CharField(blank=True, default='', max_length=180, verbose_name='причина')),
                ('status', models.CharField(default='review', max_length=16, verbose_name='статус')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='directories.counterparty', verbose_name='клиент')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.sale', verbose_name='документ продажи')),
            ],
            options={
                'verbose_name': 'возврат',
                'verbose_name_plural': 'возвраты',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('title', models.CharField(max_length=255, verbose_name='задача')),
                ('assignee', models.CharField(blank=True, default='', max_length=180, verbose_name='исполнитель')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='срок')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=16, verbose_name='приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('progress', 'В работе'), ('done', 'Выполнена')], default='new', max_length=16, verbose_name='статус')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='sales.deal', verbose_name='сделка')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ('due_date',),
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date'], name='sales_sale_date_ca4177_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_sale_status_532843_idx'),
        ),
    ]
