# Generated by Django 5.2 on 2026-07-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('date', models.DateField(verbose_name='дата выписки')),
                ('file_name', models.CharField(max_length=180, verbose_name='файл')),
                ('format', models.CharField(default='1C-Bank Exchange', max_length=60, verbose_name='формат')),
                ('rows_count', models.PositiveIntegerField(default=0, verbose_name='операций')),
                ('incoming', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='приход')),
                ('outgoing', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='расход')),
                ('matched', models.PositiveIntegerField(default=0, verbose_name='сопоставлено')),
                ('status', models.CharField(choices=[('loaded', 'Загружена'), ('processed', 'Обработана')], default='loaded', max_length=16, verbose_name='статус')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'банковская выписка',
                'verbose_name_plural': 'банковские выписки',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('period_key', models.CharField(max_length=10, verbose_name='ключ периода')),
                ('period', models.CharField(max_length=40, verbose_name='период')),
                ('kind', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='expense', max_length=16, verbose_name='вид')),
                ('item', models.CharField(max_length=150, verbose_name='статья')),
                ('plan', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='план')),
                ('fact', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='факт')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'статья бюджета',
                'verbose_name_plural': 'бюджет',
                'ordering': ('-period_key', 'kind', 'item'),
            },
        ),
        migrations.CreateModel(
            name='CashOrder',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('kind', models.CharField(choices=[('in', 'Приходный'), ('out', 'Расходный')], default='in', max_length=8, verbose_name='вид')),
                ('date', models.DateField(verbose_name='дата')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('person', models.CharField(blank=True, default='', max_length=200, verbose_name='от кого / кому')),
                ('basis', models.CharField(blank=True, default='', max_length=255, verbose_name='основание')),
                ('cashier', models.CharField(blank=True, default='', max_length=180, verbose_name='кассир')),
                ('status', models.CharField(default='posted', max_length=16, verbose_name='статус')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_orders', to='directories.counterparty', verbose_name='контрагент')),
            ],
            options={
                'verbose_name': 'кассовый ордер',
                'verbose_name_plural': 'кассовые ордера',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('kind', models.CharField(choices=[('in', 'Поступление'), ('out', 'Списание')], default='out', max_length=8, verbose_name='направление')),
                ('date', models.DateField(verbose_name='дата')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('purpose', models.CharField(blank=True, default='', max_length=400, verbose_name='назначение платежа')),
                ('account', models.CharField(blank=True, default='', max_length=40, verbose_name='расчётный счёт')),
                ('bank', models.CharField(blank=True, default='', max_length=150, verbose_name='банк')),
                ('matched', models.BooleanField(default=False, verbose_name='сопоставлен')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('executed', 'Исполнен')], default='new', max_length=16, verbose_name='статус')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='directories.counterparty', verbose_name='контрагент')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['date'], name='finance_pay_date_091c4c_idx'), models.Index(fields=['kind'], name='finance_pay_kind_dc5897_idx')],
            },
        ),
    ]
