# Generated by Django 5.2 on 2026-07-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('period_key', models.CharField(max_length=10, verbose_name='ключ периода')),
                ('period', models.CharField(max_length=40, verbose_name='период')),
                ('employee_name', models.CharField(blank=True, default='', max_length=180, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, default='', max_length=120, verbose_name='должность')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='оклад')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='премия')),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='начислено')),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='подоходный налог')),
                ('social', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='соцфонд')),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='к выплате')),
                ('status', models.CharField(choices=[('calculated', 'Рассчитано'), ('paid', 'Выплачено')], default='calculated', max_length=16, verbose_name='статус')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='дата выплаты')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='directories.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'расчёт зарплаты',
                'verbose_name_plural': 'расчёты зарплаты',
                'ordering': ('-period_key', 'employee_name'),
                'unique_together': {('period_key', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('employee_name', models.CharField(blank=True, default='', max_length=180, verbose_name='ФИО')),
                ('date', models.DateField(verbose_name='дата')),
                ('type', models.CharField(choices=[('work', 'Рабочий день'), ('vacation', 'Отпуск'), ('sick', 'Больничный')], default='work', max_length=16, verbose_name='вид дня')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='часов')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='directories.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'запись табеля',
                'verbose_name_plural': 'табель рабочего времени',
                'ordering': ('-date',),
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
