# Generated by Django 5.2 on 2026-07-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата')),
                ('responsible', models.CharField(blank=True, default='', max_length=180, verbose_name='ответственный')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('done', 'Завершена')], default='draft', max_length=16, verbose_name='статус')),
                ('lines', models.JSONField(blank=True, default=list, verbose_name='позиции')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='directories.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'инвентаризация',
                'verbose_name_plural': 'инвентаризации',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='позиции')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='оплачено')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='дата поставки')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('sent', 'Отправлен'), ('received', 'Получен'), ('cancelled', 'Отменён')], default='new', max_length=16, verbose_name='статус')),
                ('manager', models.CharField(blank=True, default='', max_length=180, verbose_name='ответственный')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='directories.counterparty', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'заказ поставщику',
                'verbose_name_plural': 'заказы поставщикам',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='наименование')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='количество')),
                ('unit', models.CharField(blank=True, default='шт', max_length=20, verbose_name='единица')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('need', models.DateField(blank=True, null=True, verbose_name='нужно к дате')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('review', 'На проверке'), ('approved', 'Одобрена'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=16, verbose_name='статус')),
                ('comment', models.TextField(blank=True, default='', verbose_name='обоснование')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='directories.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'заявка на закупку',
                'verbose_name_plural': 'заявки на закупку',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата')),
                ('type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Отгрузка'), ('move', 'Перемещение'), ('writeoff', 'Списание')], default='in', max_length=16, verbose_name='операция')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='наименование товара')),
                ('unit', models.CharField(blank=True, default='шт', max_length=20, verbose_name='единица')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='цена')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='причина / основание')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_out', to='directories.warehouse', verbose_name='склад-источник')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='directories.product', verbose_name='товар')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_in', to='directories.warehouse', verbose_name='склад-получатель')),
            ],
            options={
                'verbose_name': 'движение товара',
                'verbose_name_plural': 'движения товара',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='количество')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='directories.product', verbose_name='товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='directories.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'остаток',
                'verbose_name_plural': 'остатки',
                'ordering': ('product__name',),
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
