# Generated by Django 5.2 on 2026-07-29 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('kind', models.CharField(choices=[('info', 'Информация'), ('ok', 'Успех'), ('warn', 'Внимание'), ('danger', 'Важно')], default='info', max_length=16, verbose_name='вид')),
                ('icon', models.CharField(blank=True, default='bell', max_length=32, verbose_name='иконка')),
                ('title', models.CharField(max_length=180, verbose_name='заголовок')),
                ('text', models.CharField(blank=True, default='', max_length=400, verbose_name='текст')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('link', models.CharField(blank=True, default='', max_length=120, verbose_name='ссылка')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ('-ts',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(max_length=40, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата')),
                ('type', models.CharField(choices=[('purchase', 'Покупка'), ('payment', 'Оплата'), ('cash', 'Выдача денег'), ('document', 'Создание документа'), ('repair', 'Ремонт'), ('supply', 'Закупка')], default='purchase', max_length=24, verbose_name='тип')),
                ('type_name', models.CharField(blank=True, default='', max_length=60, verbose_name='название типа')),
                ('subject', models.CharField(max_length=255, verbose_name='тема заявки')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('department', models.CharField(blank=True, default='', max_length=120, verbose_name='отдел')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=16, verbose_name='приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('review', 'На проверке'), ('approved', 'Одобрена'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=16, verbose_name='статус')),
                ('route', models.JSONField(blank=True, default=list, verbose_name='маршрут согласования')),
                ('comment', models.TextField(blank=True, default='', verbose_name='комментарий')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'внутренняя заявка',
                'verbose_name_plural': 'внутренние заявки',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('user', models.CharField(blank=True, default='', max_length=180, verbose_name='пользователь')),
                ('role', models.CharField(blank=True, default='', max_length=40, verbose_name='роль')),
                ('action', models.CharField(blank=True, default='', max_length=32, verbose_name='действие')),
                ('action_text', models.CharField(blank=True, default='', max_length=180, verbose_name='описание действия')),
                ('entity', models.CharField(blank=True, default='', max_length=60, verbose_name='коллекция')),
                ('entity_title', models.CharField(blank=True, default='', max_length=120, verbose_name='объект')),
                ('entity_id', models.CharField(blank=True, default='', max_length=48, verbose_name='идентификатор объекта')),
                ('label', models.CharField(blank=True, default='', max_length=180, verbose_name='метка объекта')),
                ('details', models.CharField(blank=True, default='', max_length=255, verbose_name='изменённые поля')),
                ('ip', models.CharField(blank=True, default='', max_length=64, verbose_name='IP-адрес')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('user_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL, verbose_name='учётная запись')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'аудит действий',
                'ordering': ('-ts',),
                'indexes': [models.Index(fields=['-ts'], name='workflow_au_ts_ebf1d4_idx'), models.Index(fields=['entity'], name='workflow_au_entity_fa4135_idx')],
            },
        ),
    ]
