# Generated by Django 5.2 on 2026-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='theme',
            field=models.CharField(default='dark', max_length=16, verbose_name='тема'),
        ),
    ]
