# Generated by Django 5.2 on 2026-07-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='код счёта')),
                ('name', models.CharField(max_length=180, verbose_name='наименование')),
                ('kind', models.CharField(choices=[('A', 'Активный'), ('P', 'Пассивный'), ('AP', 'Активно-пассивный')], default='A', max_length=4, verbose_name='вид')),
                ('parent', models.CharField(blank=True, default='', max_length=16, verbose_name='родительский счёт')),
                ('opening', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='входящее сальдо')),
            ],
            options={
                'verbose_name': 'счёт',
                'verbose_name_plural': 'план счетов',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('key', models.CharField(max_length=10, verbose_name='ключ периода')),
                ('name', models.CharField(max_length=40, verbose_name='название')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='месяц')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='доходы')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='расходы')),
                ('closed', models.BooleanField(default=False, verbose_name='закрыт')),
                ('closed_by', models.CharField(blank=True, default='', max_length=180, verbose_name='кто закрыл')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='когда закрыт')),
            ],
            options={
                'verbose_name': 'период',
                'verbose_name_plural': 'периоды',
                'ordering': ('-key',),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('name', models.CharField(max_length=120, verbose_name='налог')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ставка, %')),
                ('period_key', models.CharField(max_length=10, verbose_name='ключ периода')),
                ('period', models.CharField(max_length=40, verbose_name='период')),
                ('frequency', models.CharField(blank=True, default='', max_length=40, verbose_name='периодичность')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='налоговая база')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма налога')),
                ('due_date', models.DateField(verbose_name='срок уплаты')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('paid', 'Уплачен'), ('overdue', 'Просрочен')], default='planned', max_length=16, verbose_name='статус')),
                ('declaration', models.CharField(blank=True, default='Не сдана', max_length=40, verbose_name='декларация')),
            ],
            options={
                'verbose_name': 'налог',
                'verbose_name_plural': 'налоги',
                'ordering': ('-due_date',),
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('number', models.CharField(blank=True, default='', max_length=32, verbose_name='номер')),
                ('date', models.DateField(verbose_name='дата')),
                ('debit', models.CharField(max_length=16, verbose_name='счёт дебета')),
                ('credit', models.CharField(max_length=16, verbose_name='счёт кредита')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('content', models.CharField(max_length=255, verbose_name='содержание операции')),
                ('auto', models.BooleanField(default=False, verbose_name='создана автоматически')),
                ('posted', models.BooleanField(default=False, verbose_name='проведена')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'проводка',
                'verbose_name_plural': 'проводки',
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
