# Generated by Django 5.2 on 2026-07-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('directories', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='documents.document', verbose_name='документ-основание'),
        ),
        migrations.AddField(
            model_name='period',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация'),
        ),
        migrations.AddField(
            model_name='tax',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['date'], name='accounting__date_39b23c_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['debit'], name='accounting__debit_357c73_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['credit'], name='accounting__credit_2b0acf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('company', 'key')},
        ),
    ]
