# Generated by Django 5.2 on 2026-08-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('directories', '0002_alter_appsettings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('inv_number', models.CharField(max_length=32, verbose_name='инвентарный номер')),
                ('name', models.CharField(max_length=180, verbose_name='наименование')),
                ('group', models.CharField(choices=[('building', 'Здания и сооружения'), ('vehicle', 'Транспортные средства'), ('machine', 'Машины и оборудование'), ('computer', 'Компьютерная техника'), ('furniture', 'Мебель и инвентарь'), ('other', 'Прочие основные средства')], default='other', max_length=16, verbose_name='группа')),
                ('account', models.CharField(default='01', max_length=16, verbose_name='счёт учёта')),
                ('depreciation_account', models.CharField(default='02', max_length=16, verbose_name='счёт амортизации')),
                ('expense_account', models.CharField(default='26', max_length=16, verbose_name='счёт затрат')),
                ('commissioned_at', models.DateField(verbose_name='дата ввода в эксплуатацию')),
                ('initial_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='первоначальная стоимость')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='ликвидационная стоимость')),
                ('life_months', models.PositiveSmallIntegerField(default=60, verbose_name='срок полезного использования, мес.')),
                ('method', models.CharField(choices=[('straight', 'Линейный'), ('declining', 'Уменьшаемого остатка'), ('sumYears', 'По сумме чисел лет'), ('units', 'Производственный')], default='straight', max_length=16, verbose_name='метод амортизации')),
                ('declining_rate', models.DecimalField(decimal_places=2, default=2, max_digits=4, verbose_name='коэффициент ускорения')),
                ('total_units', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='плановая выработка')),
                ('used_units', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='фактическая выработка')),
                ('units_name', models.CharField(blank=True, default='', max_length=32, verbose_name='единица выработки')),
                ('accumulated', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='накопленная амортизация')),
                ('location', models.CharField(blank=True, default='', max_length=180, verbose_name='местонахождение')),
                ('responsible', models.CharField(blank=True, default='', max_length=180, verbose_name='материально ответственное лицо')),
                ('status', models.CharField(choices=[('operation', 'В эксплуатации'), ('conserved', 'На консервации'), ('sold', 'Продан'), ('written_off', 'Списан')], default='operation', max_length=16, verbose_name='состояние')),
                ('disposed_at', models.DateField(blank=True, null=True, verbose_name='дата выбытия')),
                ('disposal_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='причина выбытия')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='примечание')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'основное средство',
                'verbose_name_plural': 'основные средства',
                'ordering': ('inv_number',),
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.CharField(editable=False, max_length=48, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.CharField(blank=True, default='', max_length=150, verbose_name='автор')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='кто изменил')),
                ('asset_name', models.CharField(blank=True, default='', max_length=180, verbose_name='объект')),
                ('period_key', models.CharField(max_length=10, verbose_name='ключ периода')),
                ('period', models.CharField(max_length=40, verbose_name='период')),
                ('date', models.DateField(verbose_name='дата начисления')),
                ('method', models.CharField(default='straight', max_length=16, verbose_name='метод')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма амортизации')),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='выработка за период')),
                ('accumulated_after', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='накоплено после начисления')),
                ('residual_after', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='остаточная стоимость после')),
                ('posted', models.BooleanField(default=True, verbose_name='проведено')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='directories.company', verbose_name='организация')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciations', to='accounting.entry', verbose_name='проводка')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='accounting.fixedasset', verbose_name='основное средство')),
            ],
            options={
                'verbose_name': 'начисление амортизации',
                'verbose_name_plural': 'амортизация',
                'ordering': ('-period_key', 'asset_name'),
            },
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['status'], name='accounting__status_65f104_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['group'], name='accounting__group_0f2f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciation',
            index=models.Index(fields=['period_key'], name='accounting__period__b4b791_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='depreciation',
            unique_together={('asset', 'period_key')},
        ),
    ]
